export const GameGenres = {
  adventures: 'Приключенческие',
  ameritrash: 'Америтреш',
  association: 'На ассоциации',
  book: 'Книга',
  cards: 'Карточные',
  child: 'Детские',
  child_quiz: 'Детские: Викторины',
  classic: 'Классические',
  cooperate: 'Кооперативные',
  detective: 'Детективные',
  duel: 'Дуэльные',
  economical: 'Экономические',
  eurogame: 'Еврогейм',
  evening: 'Вечериночные',
  family: 'Семейные',
  fantasy: 'Фэнтези',
  fiction: 'Фантастические',
  filler: 'Филлер',
  hardcore: 'Хардкор',
  hiddenrole: 'Со скрытыми ролями',
  history: 'Исторические',
  logical: 'Логические',
  over18: '18+',
  postap: 'Постапокалипсис',
  quiz: 'Викторины',
  reaction: 'На реакцию и координацию',
  role: 'Ролевые',
  strategy: 'Стратегические',
  wargame: 'Варгеймы',
};

export const GenresIcons = {
  adventures: 'game-icons:treasure-map',
  ameritrash: 'game-icons:american-football-player',
  association: 'ooui:speech-bubbles-ltr',
  book: 'material-symbols:book',
  cards: 'game-icons:card-10-spades',
  child: 'cil:child',
  child_quiz: 'material-symbols:quiz-outline-rounded',
  classic: 'game-icons:chess-king',
  cooperate: 'streamline-ultimate:workflow-teamwork-user-high-five',
  detective: 'ph:detective',
  duel: 'game-icons:duel',
  economical: 'game-icons:gold-bar',
  eurogame: 'game-icons:wheat',
  evening: 'game-icons:party-hat',
  family: 'game-icons:family-house',
  fantasy: 'game-icons:dragon-head',
  fiction: 'game-icons:alien-egg',
  filler: 'game-icons:hourglass',
  hardcore: 'game-icons:skull-sabertooth',
  hiddenrole: 'boxicons:mask',
  history: 'game-icons:medieval-gate',
  logical: 'game-icons:brain',
  over18: 'mdi:handcuffs',
  postap: 'game-icons:nuclear',
  quiz: 'material-symbols:quiz',
  reaction: 'game-icons:stopwatch',
  role: 'game-icons:dice-twenty-faces-twenty',
  strategy: 'material-symbols:strategy-outline',
  wargame: 'healthicons:war-outline',
};
