export const API_ENDPOINTS = {
  post: '/api/posts/',
  navigationItem: '/api/navigation-item/',
  department: '/api/departments/',
  rubric: '/api/rubric/',
  event: '/api/event/',
  slides: '/api/main-slider/',
  file: '/api/file/',
  document: '/api/document/',
  book: '/api/book/',
  bookCollection: '/api/book-collection/',
  notification: '/api/notification/',
  game: '/api/games/',
  genres: '/api/games/genres',
  tag: '/api/tags/',
};
